### ISSUE TITLE
Failed to build after clone

### ISSUE THREAD

**Issue by stephenkwokcm** [vendurehq/storefront-angular-starter#22]
WARNING in Invalid constructor parameter decorator in C:/Users/admin/Desktop/eCommerce/client/node_modules/apollo-angular/fesm2015/ngApollo.js:
 () => [
    { type: NgZone },
    { type: undefined, decorators: [{ type: Optional }, { type: Inject, args: [APOLLO_OPTIONS,] }] },
    { type: undefined, decorators: [{ type: Optional }, { type: Inject, args: [APOLLO_NAMED_OPTIONS,] }] }
]

ERROR in getInternalNameOfClass() called on a non-ES5 class: expected Apollo to have an inner class declaration

**Comment by stephenkwokcm** [comment]
This likely means that the library (@angular/forms) which declares ReactiveFormsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by stephenkwokcm** [comment]
Solved it

**Comment by michaelbromley** [comment]
Glad to hear it. Is it worth explaining how you solved it in case anyone else comes across this issue?

**Comment by stephenkwokcm** [comment]
I changed the "target" to "es2015" in tsconfig.json, but I got told this configuration will not support IE 11
