### ISSUE TITLE
Add to cart Stock validation issue

### ISSUE THREAD

**Issue by DenysArkan** [vendurehq/storefront-angular-starter#24]
The add to cart button from PDP, is not in synch with the products in stock and minicart functionality.

![2021-02-04_20h51_54](https://user-images.githubusercontent.com/47108709/106941045-fa444e80-672a-11eb-8c07-e12ac4e193e3.gif)

**Comment by michaelbromley** [comment]
Thanks for the report. This might be related to https://github.com/vendure-ecommerce/vendure/issues/691
