### ISSUE TITLE
Question, what is the best way to extends functionality

### ISSUE THREAD

**Issue by zahasoftware** [vendurehq/storefront-angular-starter#27]
Just a question, 
What is the best way to extends modules or for example add modules like delivery and add new payments methods,

Considering get all updates from storefront with no clonflicts with this new modules,

I was thinking in create another angular app, but I don't know if it is the best way

Thanks all, for this work
best regards

**Comment by michaelbromley** [comment]
Hi,

The first thing to know is that this repo is not really inteded as a "library" in the same sense as npm packages. So there's no special way to use it that will allow you to easily update when changes are made to this repo.

It's mainly intended as a demo and can be used as a starting-point for your own Angular-based storefront. So if you want to use it, just treat it as a scaffold to help you get started, but once you start modifying it to your needs, you won't be able to easily "update" to any changes here without doing so manually.

But also, I don't plan on adding a lot of new features to this - I just keep it up-to-date with Vendure API changes.
