### ISSUE TITLE
How do I set the channel ? 

### ISSUE THREAD

**Issue by javib94** [vendurehq/storefront-angular-starter#45]
I would like to show different products depending from were they are connecting to my site, I just created the second channel but I founded only the "getActiveChannel" in the documentation, how do i set the channel?, is there a place where i can paste the new token channel?

**Comment by michaelbromley** [comment]
Use the `vendure-token` header as explained here: https://www.vendure.io/docs/storefront/shop-api-guide/#universal-parameters

I'll add a note about this in the developer guide > channels section too to make it more discoverable.

So for this project, you can make modifications to the `core.module.ts` file in the `apolloOptionsFactory` function. This is where you can set other headers for each request.

**Comment by javib94** [comment]
Thank you very much! That helped me a lot :)
