### ISSUE TITLE
Checkout Shipping Method 

### ISSUE THREAD

**Issue by javib94** [vendurehq/storefront-angular-starter#48]
The shipping methods aren't showing even at the demo website, first I notice at the graphql file, the query "GetEligibleShippingMethods" still has the field "price",  so I removed it, then methods appear but the error was at the moment to set it, I checked the response with interceptor class and I got 

`{
locations: Array [ {…} ],
​​​​
0: Object { line: 2, column: 3 },
​​​​​
column: 3,
​​​​​
line: 2,
​​​​​
<prototype>: Object { … },
​​​​
length: 1,
​​​​
<prototype>: Array [],
​​​
message: "ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'field list'",
​​​
path: Array [ "setOrderShippingMethod" ],
​​​​
0: "setOrderShippingMethod",
​​​
length: 1,
}`

setOrderShippingMethod is right according to documentation, so I couldn't  fix it. I commented the line 140 in the file src/app/checkout/components/checkout-shipping/checkout-shipping.component.ts 

`this.dataService.mutate<SetShippingMethod.Mutation, SetShippingMethod.Variables>(SET_SHIPPING_METHOD, {
                        id: shippingMethodId,
                    })`

It works, but the order doesn't have assigned shipping method.

**Comment by michaelbromley** [comment]
Hi, thanks for the report. I just checked and was able to complete the entire checkout flow without error. 

Possibly at the time you tried, someone had altered something in the admin area that gave rise to the error? Can you try again and see if you still get the error?
