### ISSUE TITLE
ERROR NullInjectorError: R3InjectorError(AppModule)[DataService -> Apollo -> Apollo -> Apollo]

### ISSUE THREAD

**Issue by daolvcntt** [vendurehq/storefront-angular-starter#58]
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/3265966/164983771-3ad3f92a-7615-4535-a0ca-e3f73e4a85a5.png">
I'm having a problem when running **"yarn start"**.
Please help me about that.

**Comment by michaelbromley** [comment]
Hi,
This issue is lacking some information I need to understand it better.

* Vendure version
* Any customizations you made?
* Any other infor I would need to reproduce?

**Comment by daolvcntt** [comment]
Hi @michaelbromley I'm using Vendure version 1.5.2 and updating the latest version of angular

**Comment by michaelbromley** [comment]
~OK, v1.x of Vendure is only compatible with v12 of Angular. Support for v13+ is coming in the next major release.~

Just realized what repo this is 🤦‍♂️ 

Ok then - updating Angular is an overdue task so I'm glad you're looking in to it. Did you update any other dependencies?
