### ISSUE TITLE
Embedded Video Not Showing On Angular Storefront

### ISSUE THREAD

**Issue by ashishkpaul** [vendurehq/storefront-angular-starter#72]
Issue: Same As Title
Using v0.2.2 of Angular Storefront

Admin Pannel
![Screenshot_2022-12-01_19-01-59](https://user-images.githubusercontent.com/16308863/205066405-021f0988-170a-40f5-a976-8884ee0ef10c.png)

Angular Storefront
![Screenshot_2022-12-01_19-02-30](https://user-images.githubusercontent.com/16308863/205066618-1e2a2e28-3682-4d2e-bd8a-59ac7633f765.png)

**Comment by michaelbromley** [comment]
Any errors in the console?

**Comment by ashishkpaul** [comment]
> Any errors in the console?

No sir

**Comment by Mizan3050** [comment]
Can I work on this issue?

**Comment by michaelbromley** [comment]
@Mizan3050 yes please do!

**Comment by Mizan3050** [comment]
Thanks, I have fixed the issue on my local branch. Are there any certain rules on how I can raise a PR here? This is he 1st time I am making an OS contribution.

**Comment by michaelbromley** [comment]
That was fast!
There are no special rules for this repo. Check out this general guide: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

If you have further questions feed free to ask on our Slack: https://vendure.io/slack
