### ISSUE TITLE
Demo Angular storefront same as Remix, new update?

### ISSUE THREAD

**Issue by loganess** [vendurehq/storefront-angular-starter#75]
Hello,

I am getting same storefront as Remix demo.
Same issue after pulling recent update.

Is there anyone getting same issue?
Thank you.

<img width="1563" alt="Screenshot 2022-12-12 at 11 33 51 PM" src="https://user-images.githubusercontent.com/116762656/207227836-057585d0-25ae-487b-bb0c-b5037b2abe82.png">

**Comment by michaelbromley** [comment]
Hi!
yeah I recently migrated it to Tailwind to bring the look & feel into line with the other storefront starters.
